# Generated by Django 2.2.6 on 2019-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('col_num', models.CharField(max_length=100)),
                ('col_header', models.CharField(max_length=100)),
            ],
        ),
    ]
