# Generated by Django 2.2.6 on 2019-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ftpDirectory',
            field=models.TextField(blank=True, max_length=30, verbose_name='FTP Directory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ftpPassword',
            field=models.TextField(blank=True, max_length=30, verbose_name='FTP Password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ftpURL',
            field=models.TextField(blank=True, max_length=500, verbose_name='FTP URL Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ftpUsername',
            field=models.TextField(blank=True, max_length=30, verbose_name='FTP Username'),
        ),
    ]
